server:
  port: 16001

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update


eureka:
  client:
    enabled: false

security:
  basic:
    enabled: false