server:
  port: 16001

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/eintrusty
    username: ropandi
    password: roP123.
    driver-class-name: org.postgresql.Driver
    platform: postgres


eureka:
  client:
    enabled: false

security:
  basic:
    enabled: false