server:
  port: 16001

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        use_sql_comments: false
        format_sql: true
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
  datasource:
    url: jdbc:postgresql://localhost:5432/eintrusty
    username: ropandi
    password: roP123.
    driver-class-name: org.postgresql.Driver
    platform: postgres


eureka:
  client:
    enabled: false

security:
  basic:
    enabled: false